#!/bin/bash

#returns number of opened screens with argument name
function screen_check () {
	[[ $(screen -ls | grep -c "$1")  > 0 ]]&& echo $(screen -ls | grep -c "$1") || echo "0"
}

case $1 in
	run)
		while true; do
			[[ $(screen_check agent) -eq 0 ]] && echo "Starting agent screen" && screen -dmS agent bash -c "/dog/stats"
			sleep 10
		done
	;;
	*)
		screen -r agent
	;;
esac
