#!/bin/bash
. colors
AMD_CFG="/dog/cfg/amd.cfg"
AMDMEMINFO_FILE=/tmp/amdmeminfo
LOCK_FILE="/tmp/.amd-oc.lock"

[[ ! -f $AMDMEMINFO_FILE ]] && amdmeminfo -q -s -n > $AMDMEMINFO_FILE
[[ ! -f /run/dog/gpuStats ]] && gpu-detect listJS > /run/dog/gpuStats
DEBUG=0

NAVI_VDDCI_MIN=650
NAVI_VDDCI_MAX=850
NAVI_MVDD_MIN=1100
NAVI_MVDD_MAX=1350

# Navi 20 limits
LIMIT_NAVI20_SOC_VDD_MIN=650 
LIMIT_NAVI20_SOC_VDD_MAX=1200

LIMIT_NAVI20_VDDCI_MIN=650
LIMIT_NAVI20_VDDCI_MAX=850

LIMIT_NAVI20_CVDDC_MIN=600
LIMIT_NAVI20_CVDDC_MAX=1200

LIMIT_NAVI20_MVDD_MIN=1100
LIMIT_NAVI20_MVDD_MAX=1350

LIMIT_NAVI20_CORE_CLOCK_MIN=900

DEFAULT_NAVI20_CORE_CLOCK=1300
DEFAULT_NAVI20_CORE_VOLTAGE=850
#####

listAMD=`cat /run/dog/gpuStats | jq '[.gpu[] | select(.brand == "A")]'`

function getdata() {
	for option in core_clock core_state core_voltage memory_clock memory_state memory_voltage vddci soc_vdd_max soc_clk_max memory_tweak_type fan enhanced alt; do
		if [[ `echo $1 | jq ".$option"` != null ]]; then
			option_value="`echo $1 | jq -r \".$option\"`" #double slash, because eval open it
			eval "${option^^}=\"$option_value\""
		fi
	done
	if [[ `echo $1 | jq ".memory_tweak"` != null ]]; then
		local memory_tweak="`echo $1 | jq -r \".memory_tweak\"`"
		if [[ $MEMORY_TWEAK_TYPE == 0 ]]; then
			MEMORY_TWEAK="$memory_tweak"
		else
			oldIFS="$IFS"
			IFS='
'
			IFS=${IFS:0:1}
			MEMORY_TWEAK=($memory_tweak)
			IFS="$oldIFS"
		fi
	fi
}

function PWMfan() {
	local fan=$1
	local fanAddr=$2
	#echo 0 > $fanAddr/pwm1_enable
	if [[ ! $fanAddr || ! -f  $fanAddr/pwm1_enable ]]; then
		echo "${RED}Unable to set fan speed"
	else
		if [[ $fan == "A" || $fan == 0 ]]; then
			echo 2 > $fanAddr/pwm1_enable
			echo -e "Applying ${BROWN}Fan${WHITE}\t\t${CYAN}Auto${WHITE} mode (GPU controlled)"
		else
			local range
			local fanAdapted
			echo -e "Applying ${BROWN}Fan${WHITE}\t\t${CYAN}$fan${WHITE} (${CYAN}Manual${WHITE} mode)"
			echo 1 > $fanAddr/pwm1_enable
			[[ -f  $fanAddr/pwm1_min ]] && fanMin=`cat $fanAddr/pwm1_min` || fanMin=0
			[[ -f  $fanAddr/pwm1_max ]] && fanMax=`cat $fanAddr/pwm1_max` || fanMax=255
			let range=$fanMax-$fanMin
			fanAdapted=`echo "scale=0; $fan * $range / 100 + $fanMin" | bc -l`
			echo $fanAdapted > $fanAddr/pwm1
		fi
	fi
}

function getDefaultDataNavi20() {
	#local upp=/dog/sbin/upp/upp.py
	local upp=/dog/sbin/upp/upp.py
	[[ ! $1 || ! -f $1 ]] && echo -e "${RED}Something wrong with pp_table${WHITE}" && exit 0
	local table=$1
	local uppArgs
	uppArgs+="smc_pptable/MinVoltageGfx "		# 0
	uppArgs+="smc_pptable/MaxVoltageGfx "		# 1

	uppArgs+="smc_pptable/MinVoltageSoc "		# 2
	uppArgs+="smc_pptable/MaxVoltageSoc "		# 3
 
	uppArgs+="smc_pptable/MemVddciVoltage/0 "	# 4-
	uppArgs+="smc_pptable/MemVddciVoltage/3 "	# 5

	uppArgs+="smc_pptable/MemMvddVoltage/0 "	# 6
	uppArgs+="smc_pptable/MemMvddVoltage/3 "	# 7
	
	uppArgs+="smc_pptable/FreqTableUclk/3 "		# 8
	uppArgs+="overdrive_table/max/7 "			# 9
	uppArgs+="overdrive_table/max/0 "			# 10
	
	uppArgs+="smc_pptable/FreqTableSocclk/0 "	# 11
	uppArgs+="smc_pptable/FreqTableSocclk/1 "	# 12
	
	ppData=(`$upp -p $table get $uppArgs`)

	MinVoltageGfx=`echo "scale=0; ${ppData[0]} / 4" | bc -l`
	MaxVoltageGfx=`echo "scale=0; ${ppData[1]} / 4" | bc -l`
	MinVoltageSoc=`echo "scale=0; ${ppData[2]} / 4" | bc -l`
	MaxVoltageSoc=`echo "scale=0; ${ppData[3]} / 4" | bc -l`
	MinMemVddciVoltage=`echo "scale=0; ${ppData[4]} / 4" | bc -l`
	MaxMemVddciVoltage=`echo "scale=0; ${ppData[5]} / 4" | bc -l`
	MinMemMvddVoltage=`echo "scale=0; ${ppData[6]} / 4" | bc -l`
	MaxMemMvddVoltage=`echo "scale=0; ${ppData[7]} / 4" | bc -l`
	DefMemClock=${ppData[8]}
	MaxMemClock=${ppData[9]}
	MaxCoreClock=${ppData[10]}
	MinSocClock=${ppData[11]}
	MaxSocClock=${ppData[12]}

	echo -e "Default PowerPlay table data:"
	echo -e "Core\tMax Clock $MaxCoreClock, Voltage\t$MinVoltageGfx / $MaxVoltageGfx"
	echo -e "SOC\tMin Clock $MinSocClock, Max Clock $MaxSocClock, Voltage\t$MinVoltageSoc / $MaxVoltageSoc"
	echo -e "Mem\tDefault Clock $DefMemClock, Max Clock $MaxMemClock, Voltage $MinMemMvddVoltage / $MaxMemMvddVoltage"
	echo -e "VDDCI\tVoltage $MinMemVddciVoltage / $MaxMemVddciVoltage"
	echo -e ""
}


function navi20OC() {
	#local upp=/dog/sbin/upp/upp.py
	local upp=upp
	local upp=/dog/sbin/upp/upp.py
	[[ ! $1 ]] && echo -e "${RED}Something wrong with core address${WHITE}" && exit 0
	local coreAddr=$1
	local table="$coreAddr/pp_table"

	local uppArgs="smc_pptable/FanStopTemp=0 smc_pptable/FanStartTemp=10 smc_pptable/FanZeroRpmEnable=0 "
	#upp -p $table set $uppArgs --write

	# SOC Clock
	if [[ ! -z ${SOC_CLK_MAX[$i]} && ${SOC_CLK_MAX[$i]} -gt 0 && ${SOC_CLK_MAX[$i]} -le $MaxSocClock ]]; then
		echo -e "Applying Max SOC Clock ${SOC_CLK_MAX[$i]}"
		socClock=${SOC_CLK_MAX[$i]}
	else
		echo -e "${BROWN}Max SOC Clock${WHITE} value (${SOC_CLK_MAX[$i]}) does not fit min/max, will use def. $MaxSocClock"
		socClock=$MaxSocClock
	fi
	uppArgs+="smc_pptable/FreqTableSocclk/1=$socClock "

	# SOC Min Clock	
	#local MinSocClockLocal=`echo "scale=0; ${SOC_CLK_MAX[$i]} - 100" | bc -l`
	local MinSocClockLocal=$MinSocClock
	uppArgs+="smc_pptable/FreqTableSocclk/0=$MinSocClockLocal "
		
	# SOC Voltage
	local socVdd=`echo "scale=0; $MaxVoltageSoc * 4" | bc -l` # default
	if [[ ! -z ${SOC_VDD_MAX[$i]} && ${SOC_VDD_MAX[$i]} -le $LIMIT_NAVI20_SOC_VDD_MAX ]]; then
		if [[ ${SOC_VDD_MAX[$i]} -lt $LIMIT_NAVI20_SOC_VDD_MIN ]]; then
			socVdd=`echo "scale=0; $LIMIT_NAVI20_SOC_VDD_MIN * 4" | bc -l`
			echo -e "${BROWN}Max SOC VDD${WHITE} value (${SOC_VDD_MAX[$i]}) does not fit min/max, will use def. default $LIMIT_NAVI20_SOC_VDD_MIN"
		else
			socVdd=`echo "scale=0; $SOC_VDD_MAX * 4" | bc -l`
			echo -e "Applying Max SOC VDD ${SOC_VDD_MAX[$i]}"
		fi	
	else
		echo -e "${BROWN}Max SOC VDD${WHITE} value (${SOC_VDD_MAX[$i]}) does not fit min/max, will use def. $MaxVoltageSoc"
	fi
	uppArgs+="smc_pptable/MaxVoltageSoc=$socVdd "

	# VDDCI Voltage
	local vlt_vddci=`echo "scale=0; $MaxMemVddciVoltage * 4" | bc -l` # default
	if [[ ! -z ${VDDCI[$i]} && ${VDDCI[$i]} -le $LIMIT_NAVI20_VDDCI_MAX ]]; then
		if [[ ${VDDCI[$i]} -lt $LIMIT_NAVI20_VDDCI_MIN ]]; then
			echo -e "${BROWN}VDDCI${WHITE} value (${VDDCI[$i]}) does not fit min/max, will use def. $LIMIT_NAVI20_VDDCI_MIN"
			vlt_vddci=`echo "scale=0; $LIMIT_NAVI20_VDDCI_MIN * 4" | bc -l`
		else
			echo -e "Applying VDDCI ${VDDCI[$i]}"
			vlt_vddci=`echo "scale=0; ${VDDCI[$i]} * 4" | bc -l`
		fi
	else
		echo -e "${BROWN}VDDCI${WHITE} value (${VDDCI[$i]}) does not fit min/max, will use def. $MaxMemVddciVoltage"
	fi
	uppArgs+="smc_pptable/MemVddciVoltage/1=${vlt_vddci} "
	uppArgs+="smc_pptable/MemVddciVoltage/2=${vlt_vddci} "
	uppArgs+="smc_pptable/MemVddciVoltage/3=${vlt_vddci} "

	# MVDD
	local mvdd=`echo "scale=0; $MaxMemMvddVoltage * 4" | bc -l` # default
	if [[ ${MEMORY_VOLTAGE[$i]} -gt 0 && ${MEMORY_VOLTAGE[$i]} -le $LIMIT_NAVI20_MVDD_MAX ]]; then
       if [[ ${MEMORY_VOLTAGE[$i]} -lt $NAVI_MVDD_MIN ]]; then
           mem_vdd=`echo "scale=0; $LIMIT_NAVI20_MVDD_MIN * 4" | bc -l`
       else
           mem_vdd=`echo "scale=0; $MEMORY_VOLTAGE * 4" | bc -l`
       fi
	fi
	uppArgs+="smc_pptable/MemMvddVoltage/1=${mvdd} "
	uppArgs+="smc_pptable/MemMvddVoltage/2=${mvdd} "
	uppArgs+="smc_pptable/MemMvddVoltage/3=${mvdd} "

	# Core Clock
	if [[ ! -z ${CORE_CLOCK[$i]} && ${CORE_CLOCK[$i]} -ge $LIMIT_NAVI20_CORE_CLOCK_MIN && ${CORE_CLOCK[$i]} -le $MaxCoreClock ]]; then
		local coreClock=${CORE_CLOCK[$i]}
	else
		echo -e "${CYAN}Core Clock${WHITE} value (${CORE_CLOCK[$i]}) does not fit min/max, will use def. $DEFAULT_NAVI20_CORE_CLOCK"
		local coreClock=$DEFAULT_NAVI20_CORE_CLOCK
	fi

	# Core Voltage
	if [[ ! -z ${CORE_VOLTAGE[$i]} && ${CORE_VOLTAGE[$i]} -ge $LIMIT_NAVI20_CVDDC_MIN && ${CORE_VOLTAGE[$i]} -le $MaxVoltageGfx ]]; then
		local vddc=${CORE_VOLTAGE[$i]}
	else
		echo -e "${BROWN}Core Voltage${WHITE} value (${CORE_VOLTAGE[$i]}) does not fit min/max, will use def. $DEFAULT_NAVI20_CORE_VOLTAGE"
		local vddc=$DEFAULT_NAVI20_CORE_VOLTAGE
	fi

	$upp -p $table set_curve_gfx $coreClock $vddc --write > /dev/null 2>&1
	$upp -p $table set $uppArgs --write > /dev/null 2>&1
	exitcode=$?
	[[ $exitcode -ne 0 ]] && echo -e "${RED}Something goes wrong while applying command${WHITE}" && echo "upp -p $table set $uppArgs --write"

	#exit 0
	# Memory clock
	if [[ ! -z ${MEMORY_CLOCK[$i]} && ${MEMORY_CLOCK[$i]} -le $MaxMemClock ]]; then
		local memoryClock=${MEMORY_CLOCK[$i]}
	else
		echo -e "${CYAN}Memory Clock${WHITE} value (${MEMORY_CLOCK[$i]}) does not fit min/max, will use def. $DefMemClock"
		local memoryClock=$DefMemClock
	fi
	echo -e "Applying ${BROWN}Core Clock${WHITE}\t${CYAN}$coreClock${WHITE}"
	echo -e "Applying ${BROWN}Memory Clock${WHITE}\t${CYAN}$memoryClock${WHITE}"
	local pp_dpm_sclk_lastState=`tail -n 1 $coreAddr/pp_dpm_sclk | sed 's/^\([0-9]*\):.*/\1/'`
	local pp_dpm_mclk_lastState=`tail -n 1 $coreAddr/pp_dpm_mclk | sed 's/^\([0-9]*\):.*/\1/'`
	local pp_dpm_socclk_lastState=`tail -n 1 $coreAddr/pp_dpm_socclk | sed 's/^\([0-9]*\):.*/\1/'`

	echo 5 > $coreAddr/pp_power_profile_mode 2> /dev/null
	echo "manual" > $coreAddr/power_dpm_force_performance_level 2> /dev/null
	echo "s 1 $coreClock" > $coreAddr/pp_od_clk_voltage 2> /dev/null
	echo "m 1 $memoryClock" > $coreAddr/pp_od_clk_voltage 2> /dev/null
	echo "vc 2 $coreClock" > $coreAddr/pp_od_clk_voltage 2> /dev/null
	echo "c" > $coreAddr/pp_od_clk_voltage 2> /dev/null

	echo $pp_dpm_sclk_lastState > $coreAddr/pp_dpm_sclk 2> /dev/null
	echo $pp_dpm_mclk_lastState > $coreAddr/pp_dpm_mclk 2> /dev/null
	echo $pp_dpm_socclk_lastState > $coreAddr/pp_dpm_socclk 2> /dev/null

	if [[ $DEBUG -eq 1 ]]; then
		echo -e "UPP arguments:\n$uppArgs"
		echo ""
		echo "echo \"s 1 $coreClock\" > $coreAddr/pp_od_clk_voltage"
		echo "echo \"m 1 $memoryClock\" > $coreAddr/pp_od_clk_voltage 2> /dev/null"
		echo "echo \"vc 2 $coreClock\" > $coreAddr/pp_od_clk_voltage 2> /dev/null"
		echo "echo \"c\" > $coreAddr/pp_od_clk_voltage 2> /dev/null"
		
		echo "echo $pp_dpm_sclk_lastState > $coreAddr/pp_dpm_sclk"
		echo "echo $pp_dpm_socclk_lastState > $coreAddr/pp_dpm_socclk"
		echo "echo $pp_dpm_mclk_lastState > $coreAddr/pp_dpm_mclk"		
	fi
}

if  [[ -e $LOCK_FILE ]]; then
	pid=`cat $LOCK_FILE`
	ps --pid $pid &>/dev/null
	[[ $? == 0 ]] && echo -e "${RED}It seems another copy of AMD Overclocking script is already running\nCooldown a bit :)${WHITE}" && exit 1
fi
echo $$ > $LOCK_FILE

n=`echo $listAMD | jq '.|length'`

[[ $n == 0 ]]&& echo $(date --rfc-3339=seconds)" no AMD GPU(s) detected, exiting" && rm $LOCK_FILE && exit 1
echo -e $(date --rfc-3339=seconds)" $n "$LIGHTRED"AMD"$WHITE" GPU detected"

if [[ ! -z $1 && $1 != "--firstrun" ]]; then
	echo "Overclocking config given in arguments"
	getdata "$1"
else
	[[ ! -f $AMD_CFG ]]&& echo $(date --rfc-3339=seconds)" configuration file $AMD_CFG does not exist, exiting" && rm $LOCK_FILE && exit 1
	cfg=`cat $AMD_CFG`
	echo $cfg | jq '.'  > /dev/null 2>&1
	exitcode="$?"
	if [[ $exitcode -eq 0 ]]; then
		echo "Overclocking config in JSON format (or empty)"
		getdata "$cfg"
	else
		echo "OverClocking config in BASH format"
		. $AMD_CFG
	fi
fi
#SOC_VDD_MAX="800 770 800 770 800 800 770 780 780"
#SOC_CLK_MAX=950
#OC arrays
CORE_CLOCK=($CORE_CLOCK)
CORE_STATE=($CORE_STATE)
CORE_VOLTAGE=($CORE_VOLTAGE)
MEMORY_CLOCK=($MEMORY_CLOCK)
MEMORY_STATE=($MEMORY_STATE)
MEMORY_VOLTAGE=($MEMORY_VOLTAGE)
VDDCI=($VDDCI)
SOC_VDD_MAX=($SOC_VDD_MAX)
SOC_CLK_MAX=($SOC_CLK_MAX)
[[ ! $FAN ]]&& FAN[0]="A"
FAN=($FAN)

for (( i=0; $i < $n; ++i )); do
	[[ ! ${CORE_CLOCK[$i]} && ! -z ${CORE_CLOCK[0]} ]]&& CORE_CLOCK[$i]=${CORE_CLOCK[-1]}
	[[ ! ${CORE_STATE[$i]} && ! -z ${CORE_STATE[0]} ]]&& CORE_STATE[$i]=${CORE_STATE[-1]}
	[[ ! ${CORE_VOLTAGE[$i]} && ! -z ${CORE_VOLTAGE[0]} ]]&& CORE_VOLTAGE[$i]=${CORE_VOLTAGE[-1]}
	[[ ! ${MEMORY_CLOCK[$i]} && ! -z ${MEMORY_CLOCK[0]} ]]&& MEMORY_CLOCK[$i]=${MEMORY_CLOCK[-1]}
	[[ ! ${MEMORY_STATE[$i]} && ! -z ${MEMORY_STATE[0]} ]]&& MEMORY_STATE[$i]=${MEMORY_STATE[-1]}
	[[ ! ${MEMORY_VOLTAGE[$i]} && ! -z ${MEMORY_VOLTAGE[0]} ]]&& MEMORY_VOLTAGE[$i]=${MEMORY_VOLTAGE[-1]}
	[[ ! ${SOC_VDD_MAX[$i]} && ! -z ${SOC_VDD_MAX[0]} ]]&& SOC_VDD_MAX[$i]=${SOC_VDD_MAX[-1]}
	[[ ! ${SOC_CLK_MAX[$i]} && ! -z ${SOC_CLK_MAX[0]} ]]&& SOC_CLK_MAX[$i]=${SOC_CLK_MAX[-1]}
	[[ ! ${FAN[$i]} && ! -z ${FAN[0]} ]]&& FAN[$i]=${FAN[-1]}
done

echo "Trying to apply next settings:"
echo -e ${BROWN}"Core Clock:${WHITE}\t${CORE_CLOCK[@]}"
echo -e ${BROWN}"Core State:${WHITE}\t${CORE_STATE[@]}"
echo -e ${BROWN}"Core Voltage:${WHITE}\t${CORE_VOLTAGE[@]}"
echo -e ${BROWN}"Memory Clock:${WHITE}\t${MEMORY_CLOCK[@]}"
echo -e ${BROWN}"Memory State:${WHITE}\t${MEMORY_STATE[@]}"
echo -e ${BROWN}"Memory Voltage:${WHITE}\t${MEMORY_VOLTAGE[@]}"
echo -e ${BROWN}"MemCon Voltage:${WHITE}\t${MEMORY_VOLTAGE[@]}"
echo -e ${BROWN}"Max Soc Clock:${WHITE}\t${SOC_CLK_MAX[@]}"
echo -e ${BROWN}"MaxSoc Voltage:${WHITE}\t${SOC_VDD_MAX[@]}"

echo -en ${BROWN}"Alt. Memory OC:${WHITE} "
[[ $ALT -eq 1 ]] && echo "Yes" || echo "No"
echo -e ${BROWN}"Fan:${WHITE}\t\t${FAN[@]}"
echo -en ${BROWN}"Memory Tweak:${WHITE}\t"
if [[ $MEMORY_TWEAK_TYPE == 0 ]]; then
	echo "Common"
	echo "$MEMORY_TWEAK"
else
	echo "Individual"
	for (( i=0; i < ${#MEMORY_TWEAK[@]}; i++ )); do
		[[ $i > 0 ]] && echo -e "${BROWN}--------------------------${WHITE}"
		echo "${MEMORY_TWEAK[$i]}"
	done
fi

[ -t 1 ] && echo -e ${ITALIC}"\n*If there is not enough settings (i.e. you try to apply FAN 70 70 50,\nbut you have 5 GPU, last 2 GPU will use last available value = 50)"${WHITE}
echo -e $BROWN"================================================================"$WHITE

for (( i=0; i < $n; i++ )); do
	name=`echo $listAMD | jq -r ".[$i].name"`
	navi=`echo $listAMD | jq -r ".[$i].navi"`
	coreAddr=`echo $listAMD | jq -r ".[$i].coreAddr"`
	uppArgs=''

	if [[ -z $coreAddr || $coreAddr == 'null' ]]; then
		echo -e "${LIGHTRED}GPU $i: $name${WHITE}"
		echo -e "${RED}Something wrong with GPU (driver is not enabled)${WHITE}"
		echo -e "$BROWN================================================================$WHITE"
		continue
	fi
	card=`echo $coreAddr | sed 's/\/sys\/class\/drm\/card\([0-9a-z]*\)\/device/\1/'`
	fanAddr=`echo $listAMD | jq -r ".[$i].fanAddr"`
	echo -e "${LIGHTRED}GPU $i: $name${WHITE} ($coreAddr)"
	
	#wolfamdctrl -i 0 --mem-state 2 --mem-clock 2000 --core-state 4 --core-clock 1100 --volt-state 4 --vddc-table-set 900
	#wolfamdctrl -i /sys/class/drm/card5/device --core-state 3 --core-clock 1100 also works
	
	if [[ -f $coreAddr/pp_od_clk_voltage ]]; then #grub error is fixed, amdgpu.ppfeaturemask=0xffff7fff used
		if [[ -f $coreAddr/pp_table ]]; then
			if [[ -f /tmp/pp_tables/card$card/pp_table ]]; then
				#echo "Copying Power Play table to restore defaults"
				#cp /tmp/pp_tables/card$card/pp_table$coreAddr/pp_table
				#sync
				#echo "Copying Power Play table is temporary DISABLED"
				:
			else
				echo "Can\`t find saved Power Play table" #. Try to reboot"
			fi
		else
			echo "Can\`t find existing Power Play table" #. Try to reboot"
		fi
	else
		echo "Something is wrong, may be you need to upgrade to work with Power Play tables"
	fi
	
	if [[ -z $navi || $navi -eq 0 ]]; then
		[[ $name == *"Vega"* ]] && script="vegatool" || script="wolfamdctrl"
		if [[ $ENHANCED -eq 1 && $name != *"Vega"* ]]; then
			echo -e "${LIGHTRED}Enhanced overclock (for all states)${WHITE}"
			if [[ ! -z ${CORE_CLOCK[$i]} ]]; then
				dpm_state=(`echo -e $($script -i $card --show-core | grep "DPM state" | sed -e 's/://g; s/DPM state \([0-9]*\)/\1/')`)
				for ((z=1; z < ${#dpm_state[@]}; z++)); do
					$script -i $card --core-state ${dpm_state[$z]} --core-clock ${CORE_CLOCK[$i]}
				done
			fi
			if [[ ! -z ${CORE_VOLTAGE[$i]} ]]; then
				volt_states=(`echo -e $($script -i $card --show-voltage | grep "Voltage state" | sed -e 's/://g; s/.*Voltage state \([0-9]*\)/\1/')`) 
				for ((z=0; z < ${#volt_states[@]}; z++)); do
					[[ $z -gt 7 ]] && break
					$script -i $card --volt-state ${volt_states[$z]} --vddc-table-set ${CORE_VOLTAGE[$i]}
				done
			fi
			str="$script -i $card"	#for future
		else
			str="$script -i $card"
			if [[ -z ${CORE_STATE[$i]} || ${CORE_STATE[$i]} == "A" ]]; then
				CORE_STATE[$i]=5 #if Core State is not set, use default
			fi
			
			if [[ ${CORE_CLOCK[$i]} ]]; then
				if [[ $name == *"Vega"* ]]; then
					if [[ ${CORE_STATE[$i]} ]]; then
						maxCoreClock=`echo "scale=0; ${CORE_CLOCK[$i]} + (7 - ${CORE_STATE[$i]})*10" | bc -l`
						for (( vega_state=1; $vega_state <= 7; vega_state++ )); do
							vega_clock=`echo "scale=0; $maxCoreClock - (7-$vega_state)*10" | bc -l`
							$script -i $card --core-state $vega_state --core-clock $vega_clock | sed -e "s/^MyTool 0.0.1$//; /^\s*$/d; s/'//g"
						done
					else
						for (( vega_state=1; $vega_state <= 7; vega_state++ )); do
							vega_clock=`echo "scale=0; ${CORE_CLOCK[$i]} - (7-$vega_state)*10" | bc -l`
							$script -i $card --core-state $vega_state --core-clock $vega_clock | sed -e "s/^MyTool 0.0.1$//; /^\s*$/d; s/'//g"
							#echo "$vega_state = $vega_clock"
						done
					fi
				else
					str="$str --core-state ${CORE_STATE[$i]} --core-clock ${CORE_CLOCK[$i]}"
				fi
			fi
			if [[ ${CORE_VOLTAGE[$i]} ]]; then
				#if [[ $name != *"Vega"* }}$ENHANCED -eq 1 ]]; then
					volt_state=`echo -e $($script -i $card --show-core | grep "DPM state ${CORE_STATE[$i]}" -A1) \
					| sed -e 's/)//g; s/.*entry \([0-9]*\)/\1/'`
					str="$str --volt-state $volt_state --vddc-table-set ${CORE_VOLTAGE[$i]}"
				#fi
				
			fi
		fi
		#str="$script -i $card"
		
	
		if [[ -z ${MEMORY_STATE[$i]} || ${MEMORY_STATE[$i]} == "A" ]]; then
			MEMORY_STATE[$i]=`$script -i $card --show-mem | grep -E "Memory state ([0-9]+):" | tail -n 1 | sed "s/Memory state \([0-9]*\).*/\1/"`
		fi

		if [[ ! -z ${MEMORY_CLOCK[$i]} ]]; then
			str="$str --mem-state ${MEMORY_STATE[$i]} --mem-clock ${MEMORY_CLOCK[$i]}"
		fi

		if [[ $name != *"Vega"* ]]; then
			[[ $ALT -eq 1 && ! -z ${MEMORY_VOLTAGE[$i]} ]] && str="$str --vddci ${MEMORY_VOLTAGE[$i]}"
		fi
		
		[[ $(echo $str | awk '{print length}') -gt 30 ]] && echo "$str" && bash -c "$str" | sed -e "s/^MyTool 0.0.1$//; /^\s*$/d; s/'//g"
		#29 is "wolfamdctrl -i 5", so it`s useless to do		

		if [[ $name == *"Vega"* ]]; then
			dataArr=(`upp -p $coreAddr/pp_table get MclkDependencyTable/NumEntries SocclkDependencyTable/NumEntries`)
			maxMemState=$(( dataArr[0] - 1 ))
			
			uppArgs=
			if [[ $ENHANCED -eq 1 ]]; then
				coreVoltageAdopted=`echo "scale=2; ${CORE_VOLTAGE[$i]}/1000" | bc -l`
				echo "atitool -i=$i -vddcr_soc=$coreVoltageAdopted"
				atitool -i=$i -vddcr_soc=$coreVoltageAdopted
				bash -c "sleep 20 && atitool -i=$i -vddcr_soc=$coreVoltageAdopted" &
			fi
			
			if [[ ! -z ${MEMORY_VOLTAGE[$i]} && ! -z ${MEMORY_STATE[$i]} && ! -z ${MEMORY_CLOCK[$i]} ]]; then
				uppArgs+="VddmemLookupTable/0/Vdd=${MEMORY_VOLTAGE[$i]} "
				if [[ $ENHANCED -eq 1 ]]; then
					adoptedMvdd=`echo "scale=2; ${MEMORY_VOLTAGE[$i]}/1000" | bc -l`
					echo "atitool -i=$i -vddcr_hbm=$adoptedMvdd"
					atitool -i=$i -vddcr_hbm=$adoptedMvdd
				fi
				
			fi
			if [[ ! -z ${VDDCI[$i]} ]]; then
		   		uppArgs+="VddciLookupTable/0/Vdd=${VDDCI[$i]} "
	
			fi

			#if [[ ! -z ${MEMORY_CLOCK[$i]} ]]; then
			#	memClock=${MEMORY_CLOCK[$i]}
			#	uppArgs=
			#	for ((y=$maxMemState; y >= 1; y--)); do
			#		uppArgs+="MclkDependencyTable/${y}/VddInd=1 "
			#		uppArgs+="MclkDependencyTable/${y}/MemClk=$(( memClock*100 )) "
			#	done
			#fi

			[[ ! -z $uppArgs ]] && upp -p $coreAddr/pp_table set $uppArgs --write
			#upp -p $coreAddr/pp_table set $uppArgs --write
		else
			if [[ $ALT -ne 1 ]]; then 
				if [[ ! -z ${MEMORY_VOLTAGE[$i]} && ! -z ${MEMORY_STATE[$i]} && ! -z ${MEMORY_CLOCK[$i]} ]]; then
					mem_str="m ${MEMORY_STATE[$i]} ${MEMORY_CLOCK[$i]} ${MEMORY_VOLTAGE[$i]}"
					echo "$mem_str > $coreAddr/pp_od_clk_voltage"
					echo "$mem_str" >$coreAddr/pp_od_clk_voltage
					echo "c" > $coreAddr/pp_od_clk_voltage
				fi
			fi
		fi

		if [[ $MEMORY_TWEAK_TYPE == 0 ]]; then
			amdmemtweak --i $i $MEMORY_TWEAK
		else
			#no need to use if args are too short
			[[ ${#MEMORY_TWEAK[$i]} -gt 4 ]] && amdmemtweak --i $i ${MEMORY_TWEAK[$i]} || echo -e "${RED}There are no AMDMemTweak settings for this card${WHITE}"
		fi

		
		#if [[ $name == *"Vega"* ]]; then
			#echo "manual" >$coreAddr/power_dpm_force_performance_level
			#echo 4 >$coreAddr/pp_power_profile_mode

		#	echo "echo auto > $coreAddr/power_dpm_force_performance_level"
		#	echo "auto" > $coreAddr/power_dpm_force_performance_level	
		#else
			if [[ $ENHANCED -eq 1 && $name != *"Vega"* ]]; then
				echo auto > $coreAddr/power_dpm_force_performance_level
				echo -e "${CYAN}Auto${WHITE} Core State selection (because of Enhanced OC)"
			#elif [[ $ms_trigger -eq 1 && $cs_trigger -eq 1 ]]; then
			#	echo auto > $coreAddr/power_dpm_force_performance_level
			#	echo -e "${CYAN}Auto${WHITE} Core State selection (no states given)"
			else
				echo manual > $coreAddr/power_dpm_force_performance_level
				#Core & Memory states selection
				#if [[ $cs_trigger -ne 1 ]]; then #if core state given
					echo -e "${CYAN}Manual${WHITE} Core State selection (${CYAN}P${CORE_STATE[$i]}${WHITE})."
					echo ${CORE_STATE[$i]} > $coreAddr/pp_dpm_sclk
				#fi

				#if [[ $ms_trigger -ne 1 ]]; then
					echo -e "${CYAN}Manual${WHITE} Memory State selection (${CYAN}P${MEMORY_STATE[$i]}${WHITE})."
					echo ${MEMORY_STATE[$i]} > $coreAddr/pp_dpm_mclk
				#fi
			fi
		#fi
		#Fan section
		if (( ${FAN[$i]} == "A" )); then
			echo -e "${CYAN}Auto${WHITE} fan."
			echo 0 > $fanAddr/pwm1_enable
		else 
			echo -e "${CYAN}Manual${WHITE} fan (${FAN[$i]})." 
			echo 1 > $fanAddr/pwm1_enable
			if [[ $name == *"Vega@@@"* ]]; then #Need to check
				rpm_min=`cat $fanAddr/fan1_min`
				rpm_max=`cat $fanAddr/fan1_max`
				fan_target=`echo "scale=0; ${FAN[$i]} * $rpm_max / 100" | bc -l`
				[[ $fan_target -ge $rpm_max ]] && fan_target=`echo "$rpm_max - 1" | bc -l`
				[[ $fan_target -lt $rpm_min ]] && fan_target=`echo "$rpm_min + 1" | bc -l`
				echo $fan_target >$fanAddr/fan1_target
			else
				let fan_adapted[$i]=`echo "scale=0; ${FAN[$i]}*255/100" | bc -l` #fan power is beetween 0 and 255
				echo ${fan_adapted[$i]} > $fanAddr/pwm1
			fi
		fi
	#elif [[ $name == *"5700"* || $name == *"5500"* || $name == *"5600"* ]]; then
	elif [[ $navi -lt 20 ]]; then #this is NAVI 10
		echo "Detected NAVI$navi GPU"
		echo $coreAddr
		echo "manual" > $coreAddr/power_dpm_force_performance_level
		uppArgs=""

		uppArgs+="smc_pptable/FanStopTemp=0 "
		uppArgs+="smc_pptable/FanStartTemp=10 "

		#uppArgs+="smc_pptable/FanTargetTemperature=0 "
		
		uppArgs+="smc_pptable/FanZeroRpmEnable=0 "
		uppArgs+="smc_pptable/MinVoltageGfx=2400 "
		#uppArgs+="smc_pptable/MinVoltageUlvGfx=2400 "
		#uppArgs+="smc_pptable/MinVoltageSoc=2400 "


		#uppArgs+="smc_pptable/MinVoltageSoc=2800 "
		#upp -p /sys/class/drm/card7/device/pp_table dump | grep Soc
		if [[ ! -z ${SOC_VDD_MAX[$i]} ]]; then
			if [[ ${SOC_VDD_MAX[$i]} -ge $NAVI_VDDCI_MIN && ${SOC_VDD_MAX[$i]} -le $NAVI_VDDCI_MAX ]]; then
		   		soc_vdd_max=$((${SOC_VDD_MAX[$i]} * 4 ))
				uppArgs+="smc_pptable/MaxVoltageSoc=$soc_vdd_max "
	   		fi
		fi

		if [[ ! -z ${SOC_CLK_MAX[$i]} ]]; then
			uppArgs+="smc_pptable/FreqTableSocclk/1=${SOC_CLK_MAX[$i]} "
			uppArgs+="smc_pptable/FreqTableSocclk/2=${SOC_CLK_MAX[$i]} "
			uppArgs+="smc_pptable/FreqTableSocclk/3=${SOC_CLK_MAX[$i]} "
		fi

		if [[ ${VDDCI[$i]} -ge $NAVI_VDDCI_MIN && ${VDDCI[$i]} -le $NAVI_VDDCI_MAX ]]; then
       		vlt_vddci=$((${VDDCI[$i]} * 4 ))
			uppArgs+="smc_pptable/MemVddciVoltage/1=${vlt_vddci} "
			uppArgs+="smc_pptable/MemVddciVoltage/2=${vlt_vddci} "
			uppArgs+="smc_pptable/MemVddciVoltage/3=${vlt_vddci} "
   		fi
	    if [[ ${MEMORY_VOLTAGE[$i]} -ge $NAVI_MVDD_MIN && ${MEMORY_VOLTAGE[$i]} -le $NAVI_MVDD_MAX ]]; then
			vlt_mvdd=$((${MEMORY_VOLTAGE[$i]} * 4 ))
			uppArgs+="smc_pptable/MemMvddVoltage/1=${vlt_mvdd} "
			uppArgs+="smc_pptable/MemMvddVoltage/2=${vlt_mvdd} "
			uppArgs+="smc_pptable/MemMvddVoltage/3=${vlt_mvdd} "
    	fi

		[[ ! -z ${MEMORY_CLOCK[$i]} && ${MEMORY_CLOCK[$i]} -gt 650 ]] && odLimit=${MEMORY_CLOCK[$i]} || odLimit=960
		uppArgs+="overdrive_table/max/8=$odLimit "
		uppArgs+="overdrive_table/min/3=650 "
		uppArgs+="overdrive_table/min/5=650 "
		uppArgs+="overdrive_table/min/7=650"

		#echo "upp -p $coreAddr/pp_table set $uppArgs --write"
		upp -p $coreAddr/pp_table set $uppArgs --write

		[[ ! -z ${MEMORY_CLOCK[$i]} ]] && echo "m 1 ${MEMORY_CLOCK[$i]}" > $coreAddr/pp_od_clk_voltage

		if [[ ! -z ${CORE_CLOCK[$i]} ]]; then
			echo "s 1 ${CORE_CLOCK[$i]}" > $coreAddr/pp_od_clk_voltage

			if [[ ! -z ${CORE_VOLTAGE[$i]} ]]; then
				#[[ ${CORE_VOLTAGE[$i]} -gt 725 ]] &&
				echo "vc 1 $((${CORE_CLOCK[$i]}-100)) $((${CORE_VOLTAGE[$i]}-25))" > $coreAddr/pp_od_clk_voltage
				echo "vc 2 ${CORE_CLOCK[$i]} ${CORE_VOLTAGE[$i]}" > $coreAddr/pp_od_clk_voltage
				echo c > $coreAddr/pp_od_clk_voltage
			fi
		fi
		echo "c" > $coreAddr/pp_od_clk_voltage

		#Fan section
		echo 0 > $fanAddr/pwm1_enable
		if [[ ${FAN[$i]} == "A" ]]; then
			echo -e "${CYAN}Auto${WHITE} fan."
		else
			echo -e "${CYAN}Manual${WHITE} fan (${FAN[$i]})." 
			#if [[ $navi -eq 10 ]]; then
				echo 1 > $fanAddr/pwm1_enable
				let fan_adapted=${FAN[$i]}*255/100 #fan power is beetween 0 and 255
				[[ $fan_adapted -gt 255 ]] && fan_adapted=255
				[[ $fan_adapted -lt 0 ]] && fan_adapted=0
				echo $fan_adapted > $fanAddr/pwm1
			#else
			#	echo 1 > $fanAddr/fan1_enable
			#	echo 1 > $fanAddr/pwm1_enable
			#	
			#	[[ -f  $fanAddr/fan1_min ]] && rpm_min=`cat $fanAddr/fan1_min` || rpm_min=0
			#	[[ -f  $fanAddr/fan1_max ]] && rpm_max=`cat $fanAddr/fan1_max` || rpm_max=3400
			#
			#	fan_target=`echo "scale=0; ${FAN[$i]} * $rpm_max / 100" | bc -l`
			#	[[ $fan_target -ge $rpm_max ]] && fan_target=`echo "$rpm_max - 1" | bc -l`
			#	[[ $fan_target -lt $rpm_min ]] && fan_target=`echo "$rpm_min + 1" | bc -l`
			#	echo $fan_target > $fanAddr/fan1_target
			#fi
		fi
	elif [[ $navi -ge 20 ]]; then
		getDefaultDataNavi20 $coreAddr/pp_table
		navi20OC $coreAddr
		PWMfan ${FAN[$i]} $fanAddr
	else
		echo "Unknkown GPU"
	fi

	echo -e $BROWN"================================================================"$WHITE
	(( y++ ))
	unset cs_trigger ms_trigger
	#fi
done

rm $LOCK_FILE
