#!/bin/bash
RED="\e[31m"
WHITE="\e[0m"
GREEN="\e[32m"
BROWN="\e[33m"
BLUE="\e[34m"
PURPLE="\e[35m"
CYAN="\e[36m"
GRAY="\e[37m"

LIGHTRED="\e[1;31m" #good for AMD
YELLOW="\e[1;33m"
LIGHTGREEN="\e[1;32m" #good for Nvidia
LIGHTBLUE="\e[1;34m"
LIGHTPURPLE="\e[1;35m" #comments?
LIGHTCYAN="\e[1;36m" #very bright
LIGHTWHITE="\e[1;37m" #bold white

UNDERLINE="\e[4m"
ITALIC="\e[3m"
STANDART='\e[0m'

up="↗"
down="↘"

PURELINE="================================================================"
THINLINE="----------------------------------------------------------------"

PURELINE2="========================================================================"
THINLINE2="------------------------------------------------------------------------"

LINE="echo -e $BROWN================================================================$WHITE"

#echo -e $BLINK"There"$WHITE" are $n "$RED"AMD"$LIGHTRED" GPU"$YELLOW" detected"$WHITE

LF='
'
