#!/bin/bash
VARIABLES_CFG="/dog/service/variables"
. $VARIABLES_CFG
. colors

miner="$1"
batch="$2"

function check_con () {
	while true; do
  		for con in `netstat -anp | grep TIME_WAIT | grep ${APIPORT[$1]} | awk '{print $5}'`; do
			echo -e "${YELLOW}> Trying to purge previous connections${WHITE}" 
			killcx $con lo #$?>/dev/null
  		done
		netstat -anp | grep TIME_WAIT | grep ${APIPORT[$1]} &&
			continue ||
			break
	done
}

[[ -z $1 || -z $2 ]] && echo -e "${RED}No config given${WHITE}" && read answer #&& exit 1
[[ ! -f $VARIABLES_CFG ]] && echo "Configuration file $VARIABLES_CFG does not exist! Can\`t mine without configs..." && read answer

check_con $miner

while true; do
	bash -c "$batch"
	exitcode=$?
	echo "Error on miner start: exitcode $exitcode"
	if [[ $exitcode -eq 127 ]]; then
		fork=`echo $batch | sed "s#cd /.* /dog/miners/$miner/\([-.a-zA-Z0-9]*\)/miner.*#\1#"`
		echo ">Trying to download miner by command getminer $miner $fork"
		/dog/getminer $miner $fork
	else
		echo -e "\n${RED}>Miner exited, waiting 3 seconds to restart${WHITE}\n"
	fi
	sleep 3
done
