#!/bin/bash
. /dog/colors
LOG_DIR="/dog/log"
#[[ -z $1 ]] && miner="claymore" || miner=$1
miner=$1
Miner=${miner^}
logfile="${LOG_DIR}/${miner}.log"
reboot_logfile="${LOG_DIR}/${miner}_reboot.log"
[[ -f $reboot_logfile ]] && rm $reboot_logfile #remove old reboot log

function get_lastmsg () {
	if [[ $miner == "claymore" ]]; then
		keywords="WATCHDOG|hangs"
	elif [[ $miner == "teamredminer" ]]; then
		keywords="DEAD"
	fi
	local logtext="$1"
	local raw_msg=`echo "$logtext" | grep -m1 -E "$keywords"`
	if [[ $miner == "claymore" ]]; then
		local msg=`echo "$raw_msg" | sed -e 's/.*WATCHDOG: //' | tr -dc '[:print:]'`
	elif [[ $miner == "teamredminer" ]]; then
		#local msg=`echo "$raw_msg" | sed -e 's/, will execute.*//; s/.* GPU/GPU/' | tr -dc '[:print:]'`
		local msg=`echo "$raw_msg" | sed 's/.*\(GPU [a-zA-Z0-9]*: detected DEAD ([.:a-zA-Z0-9]*)\).*/\1/' | tr -dc '[:print:]'`
	fi
	#echo "$1"
	#echo -e "\n\n#######################\n\n"
	#echo "$raw_msg"
	#echo -e "\n\n#######################\n\n"
	echo "$msg" 
}

#save last messages about hanging cards
if [[ -f $logfile ]]; then
	tail -n 100 $logfile > $reboot_logfile
	#lastmsg_raw=`tac $reboot_logfile` | grep -m1 -E "$keywords" | sed -e 's/.*WATCHDOG: //' | tr -dc '[:print:]'`
	#tac $reboot_logfile2
	lastmsg=`get_lastmsg "$(tac $reboot_logfile)"`
fi

if [[ -z $lastmsg ]]; then
	lastmsg="$Miner Reboot"
else
	lastmsg="$Miner Reboot: $lastmsg"
fi

if [[ -f $reboot_logfile ]]; then
	#return="`date --rfc-3339=seconds` `echo -e \"${GREEN} Last 50 strings of $Miner log:${WHITE}\"`$LF`tail -n 20 $reboot_logfile | cut -f 1 -d ' ' --complement`" #| sed -e 's/\"//g; /^\s*$/d;'`
	return="`tail -n 20 $reboot_logfile`"
	echo "/dog/msg \"$lastmsg\" danger \"$return\""
	/dog/msg "$lastmsg" danger "$return"
else
	echo "/dog/msg \"$lastmsg\" danger \"$return\""
	/dog/msg "$lastmsg" danger "$return"
fi
#msg "Phoenix test" danger "Test"
echo "$return" > /dog/error.log
#sleep 120
nohup bash -c 'sreboot' > /tmp/nohup.log 2>&1 &

exit 0
