#!/bin/bash
LOG="/sobaka/log/sobaka-boot.log"
AMD="amdgpu-pro-18.50-708488-ubuntu-18.04"
NVIDIA="NVIDIA-Linux-x86_64-415.27"
RIG_CFG="/sobaka/cfg/rig.cfg"
FLASH_CFG="/sobaka-flash/rig.cfg"
NVIDIASMI_FILE=/tmp/nvidiagpudetect
AMDMEMINFO_FILE=/tmp/amdmeminfo

exec &>>$LOG

function tech_info()
{
	local info="#This is some technical information\n"
	info+="hwclock: `sudo hwclock`\n"
	info+="uptime -s: `sudo uptime -s`\n"
	info+="`sudo timedatectl | sed 's/^\s*//g'`\n\n"
	info+="Hostname: `cat /etc/hostname`\n"
	info+="`ifconfig -a`"
	echo -e "$info"
}

echo "================================================================"
export LC_ALL="en_US.UTF-8"
time_start=`date +%s`
echo "$(date --rfc-3339=seconds) $0 started."

cp /sobaka/service/environment /etc/environment
. /etc/environment
export PATH=$PATH

if [[ ! -f $RIG_CFG ]]; then
	echo -n "There is no config file on rig..."
	if [[ ! -f $FLASH_CFG ]]; then
		echo " and I can\`t find it on flash."
	else
		echo " but I find it on flash."
		dos2unix -n $FLASH_CFG /tmp/rig.cfg
		. /tmp/rig.cfg
		if [[ ! -z $HOST && ! -z $RIG_ID && ! -z $PASSWD ]]; then
			cp /tmp/rig.cfg $RIG_CFG #if don`t do it, next data looks like PASSWD="12345678"MINER=
			echo -e "\n" >> $RIG_CFG
			echo "user:$PASSWD" | chpasswd #Change password
			echo "Config copied"
		else
			echo "There is no enough data in rig.cfg on flash. Check HOST, PASSWD or RIG_ID"
		fi
	fi
fi

[[ `gpu-detect AMD` -gt 0 ]] && sleep 2 && amdmeminfo -q -s > $AMDMEMINFO_FILE

if [[ ! -f /sobaka/log/firstrun.txt ]]; then
	tech_info > /sobaka/log/firstrun.txt
	netsetup -f
else
	netsetup -f
fi
/sobaka/sbin/watchdog-opendev initial
/sobaka/sbin/watchdog-qinheng initial
hello
. $RIG_CFG
if [[ ! -z $NOTIFY_ON_BOOT || $NOTIFY_ON_BOOT == 1 ]]; then
	msg "Rig booted" info "`uptime`"
fi

if [[ $USE_GRAPHIC == 1 || -z $USE_GRAPHIC ]]; then
	[[ `gpu-detect AMD` -lt 8 ]] && sudo systemctl start sobakax
fi

time_stop=`date +%s`
let "time=time_stop - time_start"
echo "$(date --rfc-3339=seconds) $0 stopped. ($time seconds)"
echo "================================================================"