#!/bin/bash
#show some info on startup
. /etc/environment
export PATH
. colors
. /sobaka/cfg/rig.cfg

LOGO="
                .--~~,__
   :-....,-------\`~~\`._.'
    \`-,,,  ,_      ;'~U'
     _,-' ,'\`-__; \'--.
    (_/'~~      ''''(;
"
LOGO=${BROWN}$LOGO${WHITE}
uname -a | sed 's/Ubuntu /Ubuntu\n/'
$LINE
echo -en "${GREEN}Sobaka version "
[[ ! -z $OS ]] && echo -e "${CYAN}$OS" || echo -e "${RED}undefined"
echo -e "$LOGO"
echo -en ${CYAN}
#ifconfig | grep -v "127.0.0.1" | grep "inet" | sed 's/.*inet \([0-9.]*\)\s.*/IP: \1/g'
ifconfig | grep -v "127.0.0.1" | grep "inet " | sed 's/.*inet \([0-9.]*\)\s.*$/\1/g' #18.04
echo -en ${WHITE}

df -h /
uptime | sed 's/^\s//'
$LINE

gpu-detect list
$LINE
echo "Some commands:"
echo -e ${CYAN}"miner [2]"${WHITE}"\t- shows first [second] miner screen"
echo -e ${CYAN}"sobaka-agent"${WHITE}"\t- show screen with stats"
echo -e ${CYAN}"wd"${WHITE}"\t\t- show watchdog screen"
echo -e ${CYAN}"Ctrl+A,D"${WHITE}"\t- detach from current screen"
echo -e ${CYAN}"sreboot"${WHITE}"\t\t- reboot system"
echo -e ${CYAN}"newsobaka"${WHITE}"\t- set new rig ID, password, host"
echo -e ""
echo -e ${RED}"amdinfo"${WHITE}"\t\t- shows AMD core, memory & voltage states"
echo -e ${GREEN}"nvidia-smi"${WHITE}"\t- shows some info about installed NVIDIA GPU"
echo -e ""
echo -e ${CYAN}"upgrade --help"${WHITE}"\t- shows how to use upgrade/downgrade"
