#!/usr/bin/env bash
sleep 2
/sobaka/xorgmake
#vncserver
#sudo -i user 
xinit /sobaka/service/xinitrc

exitcode=$?
echo ""
echo "xinit exited (exitcode=$exitcode), starting sobaka-console"

#/sobaka/sobaka-console
sudo systemctl start sobaka-console
