#!/usr/bin/env bash

FREE_SPACE_LIMIT=100

[ -t 1 ] && . colors

part_expand(){
	[[ -z $1 ]] && echo -e "${YELLOW}No drive name given${WHITE}" && return 1
	local dev_name="/dev/$1"
	local part_name=$2

	[[ -z $part_name ]] && echo -e "${YELLOW}No partition name given${WHITE}" && return 1
	local part_num=`echo $2 | sed 's/\([[:alpha:]]*\)//'`
	local dev_part="/dev/$2"
	#  echo dev=$dev_name
	#  echo part=$part_name
	#  echo num=$part_num
	#  exit 1

	echo "> Starting to repartition"
	growpart $dev_name $part_num
	if [ $? = 0 ]; then
		echo -e "${GREEN}Repartition complete${WHITE}"
	else
		echo -e "${RED}Repartition was not completed${WHITE}"
		exit 1
	fi

	echo "> Resizing filesystem"
	resize2fs $dev_part
	if [ $? = 0 ]; then
		echo -e "${GREEN}Resizing complete${WHITE}"
	else
		echo -e "${RED}Resizing was not completed${WHITE}"
		exit 1
	fi

	return 0
}


#growpart is required for this to work
function install-deps() {
	dpkg -s cloud-guest-utils > /dev/null 2>&1
	[[ $? -ne 0 ]] &&
		apt install -y cloud-guest-utils &&
		echo ""

	which growpart > /dev/null 2>&1
	[[ $? -ne 0 ]] &&
		echo "growpart not found, try to reinstall cloud-guest-utils package" &&
		exit 1
}


install-deps

PART_UUID=`cat /proc/cmdline | tr " " "\n" | grep "UUID" | sed 's/\(^root=UUID=\)//'`
#echo $PART_UUID
DISK_PART=`blkid | grep -m1 $PART_UUID | awk '{ print $1 }' | sed 's/://' | sed 's/\(^\/dev\/\)//'`

DISK_NAME=`echo ${DISK_PART} | sed 's/\([[:digit:]]\)//'`
DISK_SIZE=`cat /proc/partitions | grep -w "${DISK_NAME}" | awk '{ printf("%.f",$3/1024)}'`
PART_SIZE=`cat /proc/partitions | grep -w "${DISK_PART}" | awk '{ printf("%.f",$3/1024)}'`

echo -e "Sobaka booted from ${GREEN}$DISK_NAME${WHITE} and whole drive size is ${WHITE}$DISK_SIZE${WHITE} MB"
echo -e "Sobaka partition is ${YELLOW}$DISK_PART${WHITE} and it's size is ${WHITE}$PART_SIZE${WHITE} MB"


EXPAND_SIZE=$((DISK_SIZE-PART_SIZE-28))
if [ $EXPAND_SIZE -le ${FREE_SPACE_LIMIT} ]; then
	echo -e "${RED}Free disk space less then ${FREE_SPACE_LIMIT} MB. Stopped${WHITE}"
	exit 1
else
	echo -e "Try to auto-expand Sobaka partition by ${WHITE}${EXPAND_SIZE}${WHITE} MB up to ${WHITE}$((PART_SIZE+EXPAND_SIZE))${WHITE} MB in total"

	[ -t 1 ] && echo -e "Press Ctrl+C to stop or wait 5 seconds to continue" && read -t 5

	part_expand "$DISK_NAME" "$DISK_PART"

	if [ $? = 0 ]; then
		NEW_PART_SIZE=`cat /proc/partitions | grep -w "${DISK_PART}" | awk '{ printf("%.f",$3/1024)}'`
		echo -e "New Sobaka partition size is ${GREEN}$NEW_PART_SIZE${WHITE} MB"
	fi
fi

