#!/bin/bash
#QinHeng Electronics HL-340
RIG_CFG="/dog/cfg/rig.cfg"
TMP_FILE="/tmp/rodos"
[ -t 1 ] && . colors #source colors only if running in terminal

#if [[ `lsusb | grep -E '20a0:4173' | wc -l` -gt 0 ]]; then #grep -E '1a86:7523|5131:2007|0471:2379'

function get_data () {
	rm -f $TMP_FILE
	rodos5b $* > $TMP_FILE 2>&1
	local timer=0
	while [[ $timer -le 100 ]]; do
		if  [[ ! -z $raw_data && $raw_data != "" ]]; then
			break
		else
			local raw_data="`cat $TMP_FILE`"
		fi
		sleep 0.1
		((timer+=1))
	done
	echo "$raw_data"
}

function init () {
	ID=$(echo `get_data` | sed "s/.*ID: \([0-9]*\).*/\1/")
	#ID=`echo $raw_data | sed "s/.*ID: \([0-9]*\).*/\1/"`

	[[ $ID == "Поиск устройств... Найдено RODOS-5/RODOS-6: 0" ]] && ID=""
	[[ ! -z $ID ]] && echo -e "> Rodos detected, ID ${CYAN}$ID${WHITE}" || echo "> No Rodos thermometer detected"

}

case $1 in
	--test)
		#get_data --id 6410 -r
		init
	;;
	--initial)
		init
		. $RIG_CFG
 		if [[ ! -z $ID ]]; then
			if [[ -z $THERMO_RODOS ]]; then
				echo "THERMO_RODOS=\"$ID\"" >> $RIG_CFG
				exitcode=$?
			else
				sed -i "s/THERMO_RODOS=.*$/THERMO_RODOS=\"$ID\"/" $RIG_CFG
				exitcode=$?
			fi
			[[ $exitcode -eq 0 ]] && echo "Rodos ID is written to config file" || echo "Error while writing data to config file"
		else #no rodos
			[[ ! -z $THERMO_RODOS ]] && sed -i "/THERMO_RODOS/d" $RIG_CFG
		fi
	;;
	--temp)
		if [[ -z $2 ]]; then
			echo -e "${RED}You don\`t specified device ID${WHITE}"
			rodos5b -a -r
		else
			raw_temp=$(echo `get_data --id $2 -r` | sed "s/.*T=\([0-9.]*\).*/\1/")
			[[ ! -z $raw_temp ]] && temp=`echo "scale=2;$raw_temp / 1" | bc -l` 
			echo $temp
		fi
	;;
	*|-h|--help)
		bname=`basename $0`
		echo -e "Welcome to ${CYAN}OSdog Rodos tool${WHITE}!"
		echo -e "Please find below the available parameter and arguments:"
		echo -e "--test\t\t\tCheck if there is thermometer in system"
		echo -e "--initial\t\tWrite thermometer data to rig config"
		echo -e "--temp\t\t\tCheck temperature. You need to specify device ID here"
		echo -e "\t\t\tf.e. rodos --temp 6410"
	;;
esac
