#!/bin/bash
[ -t 1 ] && . colors
RIG_CFG="/dog/cfg/rig.cfg"

function stop () {
	systemctl stop shbox
	pid=`ps -A | grep netmngr | awk '{print $1}'`
	[[ ! -z $pid ]] && kill -9 "$pid"

}

function start () {
	systemctl stop shbox
	pids=`ps -A | grep shellinaboxd | awk '{print $1}'`
	[[ ! -z $pid ]] && kill -9 $pid

	. $RIG_CFG
	[[ ! $SHBOX_DISABLE ]] && systemctl start shbox
}

case $1 in
	start)
		start
	;;
	stop)
		stop
	;;
	*)
		bname=`basename $0`
		echo -e "Usage: ${CYAN}$bname start|stop${WHITE}"
	;;
esac
