#!/usr/bin/env bash
#reboots or shutdowns the system using sysrq
#Usage: sreboot [shutdown]
[[ ! -z $2 ]] && WAKEALARM_TIMEOUT=$2 || WAKEALARM_TIMEOUT=30

if [[ $1 == "wakealarm" && ! -e /sys/class/rtc/rtc0/wakealarm ]]; then
	echo "Wakealarm is not supported by your motherboard"
	exit 1
fi


echo 1 > /proc/sys/kernel/sysrq
echo s > /proc/sysrq-trigger
echo u > /proc/sysrq-trigger

if [[ $1 == "shutdown" ]]; then
	echo "Shutting down"
	echo o > /proc/sysrq-trigger
elif [[ $1 == "wakealarm" ]]; then
	echo "Shutting down. Hope system will be rebooted after $WAKEALARM_TIMEOUT seconds"
	echo 0 > /sys/class/rtc/rtc0/wakealarm
	echo +$WAKEALARM_TIMEOUT > /sys/class/rtc/rtc0/wakealarm
	echo o > /proc/sysrq-trigger
else
	echo "Rebooting"
	echo b > /proc/sysrq-trigger
fi
