#!/bin/bash
. colors
[[ ! -z $1 ]] && version=$1 || version="3.8.4"

filegz="e1000e-$version.tar.gz"
url="https://downloadmirror.intel.com/15817/eng/$filegz"
dir="/tmp"

path="$dir/$filegz"
rm -rf $path $dir/e1000e-$version

echo -e "${GREEN}> Installing Intel's E1000E driver${WHITE}"
echo -e "${YELLOW}> Current driver "$(modinfo e1000e | grep ^version)${WHITE}

## Download

echo -e "${WHITE}> Downloading $url${WHITE}"
wget --no-check-certificate -c $url -O $path

[ $? -ne 0 ] && echo -e "${RED}Error downloading $url${WHITE}" && exit 1

## Unpack
cd /tmp
tar -xf $path
cd "$dir/e1000e-$version/src"
echo -e "${GREEN}> Building Intel's E1000E driver${WHITE}"

make
exitcode=$?
[[ $exitcode -ne 0 ]] && echo -e "${RED}> Driver building error${WHITE}" && exit 1
echo -e "${GREEN}> Driver building successfull${WHITE}"

## Install
echo -e "${GREEN}> Intel's E1000E driver kernel integration${WHITE}"
rmmod e1000e
cp ./e1000e.ko /lib/modules/$(uname -r)/kernel/drivers/net/ethernet/intel/e1000e/e1000e.ko
modprobe e1000e
update-initramfs -u
echo -e "${GREEN}> Intel's E1000E driver installed${WHITE}"
echo -e "${YELLOW}> Current driver "$(modinfo e1000e | grep ^version)${WHITE}











